---
 - name: Set up Node.js Application
   hosts: webservers
   become: yes
   tasks:
    - name: Install Node.js
      apt:
       name: nodejs
       state: present
    - name: Install npm
      apt:
       name: npm
       state: present
    - name: Deploy application files
      copy:
       src: /path/to/app/
       dest: /var/www/myapp/
       mode: '0755'
    - name: Install dependencies
      npm:
       path: /var/www/myapp/
       state: present
    - name: Start the application
      shell: nohup node /var/www/myapp/app.js &