vim hwreport.yml
---
 - name: Create a playbook 
   hosts: all
   tasks:
    - name: Download the file from the url provided
      ansible.builtin.get_url:
        url: << url >>
        dest: /root/hwreport.txt
    - name: replace the context
      ansible.builtin.replace:
        regexp: "{{ item.src }}"
        replace: "{{ item.dest }}"
        dest: /root/hwreport.txt
      loop:
       - src: "hostname"
         dest: "{{ ansible_hostname }}"
       - src: "memory"
         dest: "{{ ansible_memtotal_mb }}"
       - src: "biosversion"
         dest: "{{ ansible_bios_version }}"
       - src: "vda.size"
         dest: "{{ ansible_devices.vda.size }}"
       - src: "vdb.size"
         dest: "{{ ansible_devices.vdb.size }}"
    - name: replace the context
      ansible.builtin.replace:
         regexp: "{{ item.src }}"
         replace: "{{ item.dest }}"
         dest: /root/hwreport.txt
      loop:
       - src: "hostname"
         dest: "{{ ansible_hostname }}"
       - src: "memory"
         dest: "{{ ansible_memtotal_mb }}"
       - src: "biosversion"
         dest: "{{ ansible_bios_version }}"
       - src: "vda.size"
         dest: "{{ ansible_devices.vda.size }}"
       - src: "vdb.size"
         dest: "NONE"
      when: ansible_devices.vdb in not defined