---
 - name: Install and Configure MariaDB
   hosts: dbservers
   become: yes
   tasks:
    - name: Install MariaDB
      apt:
       name: mariadb-server
       state: present
    - name: Start MariaDB service
      service:
       name: mariadb
       state: started
       enabled: yes
    - name: Secure MariaDB installation
      mysql_secure_installation:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        root_password: "{{ mysql_root_password }}"
        set_root_password: yes
        remove_anonymous_users: yes
        disallow_root_login_remotely: yes
        remove_test_db: yes
        state: present